[package]
authors = ["Bahex"]
name = "split_read"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Bahex/split_read"
rust-version = "1.81.0"

[dependencies]
memchr = "2.7.4"
